/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndkutils_JniUtils */

#ifndef _Included_ndkutils_JniUtils
#define _Included_ndkutils_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndkutils_JniUtils
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndkutils_JniUtils_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
